MoveGroupExecuteService is Deprecated by MoveIt!
ros-industrial/universal_robot pull request #391
Opened 2018-11-12 02:30 UTC by Tianhuanyu

Replace MoveGroupExecuteService with MoveGroupExecuteTrajectoryAction following the warning.

2018-11-22 11:14 UTC, v4hn requested changes
I am not a maintainer of this repo, but one of the MoveIt maintainers, so I guess that counts as a review here :sunglasses: 

Thank you for the patch!

While it is correct that these services are deprecated (and actually removed in melodic),
the correct patch to address this is to get rid of the `capabilities` parameter altogether.
The correct default capabilities are automatically loaded on startup in kinetic+.

Please have a look at [the setup assistant template](https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch#L26) for comparison.

2019-02-21 12:54 UTC, hsd-dev reviewed
Thanks for your PR! Looks good to me as well.

2019-02-21 12:55 UTC, ipa-nhg approved these changes

2019-03-07 10:20 UTC, gavanderhoorn approved these changes
This is an ok first step. We can address @v4hn's comment in a later PR (the MoveIt configs need to be regenerated anwyay).

2019-03-07 10:20 UTC, merged